config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :projects
  resources :post_types
  resources :follows
  resources :categories
  resources :genres
  # resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  post 'users/:id/edit', to: "users#update"
  post 'posts/:id', to: "posts#update"
  get 'users/:id/getuser', to: "users#getuser"
  get 'post_types/:id/getpost_type', to: "post_types#getpost_type"
  post 'users/:id/delete', to: "users#delite"
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  # get 'about/index'
  # get 'promo/index'
resources :posts do
    collection do
      get :newshit
      get :newarticles
      get :newnews
      get :newpuzzles
      get :newreviews
      get :newportfolio
      get :newevents
      get :newnecrology
    end
    resources :answers
    resources :comments
    resources :likes
    resources :favorites
end
  resources :subscribers
  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'admin_context', to: 'admin_context#index'
  root 'promo#index'

  get "search", to: "search#search"

  get "searchpage" => "search#index", as: "search_index"

  get '/posts/hashtag/:name', to: 'posts#hashtags'

  get '/posts_by_type/:post_type_id/count/:count', to: "posts#get_posts_by_type"

  get '/posts_by_type_and_genre/:post_type_id/genre/:genre', to: "posts#get_posts_by_type_and_genre"

  get '/posts_by_type_and_user/:post_type_id/user/:user_id', to: "posts#get_posts_by_type_and_user"

  get '/projects_by_user/:user_id', to: "projects#get_projects_by_user"

  get '/newest_projects', to: "projects#get_newest_projects"

  get '/posts_by_category/:post_type_id/category/:category_id', to: "posts#get_posts_by_category"

  get '/posts/by_type/:name', to:"posts#post_type_page"


  # get `/your/api/namespace/endpoint/:withDynamicString/:forParams`, to: "posts#upload_image"

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit'
  get 'users/:id/favorites', to: 'users#favorites'
  post 'posts/:id' => 'posts#edit'
  delete 'users/:id', to: 'users#destroy'
  get 'users/:id/following', :to => "users#following", :as => :following

  resources :projects do
      resources :developers
  end
  # delete 'comments/:id', to: 'comments#destroy'
  # root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
		#require 'elasticsearch/model'
class Post < ApplicationRecord
		#scope :filter_by_user, -> (user) { where user: user }
	  #scope :filter_by_category, -> (category) { where category: category }
		scope :filter_by_starts_with, -> (title) { where("name like ?", "%#{title}%")}

		#include Elasticsearch::Model
		#include Elasticsearch::Model::Callbacks


    #searchkick



		validates :content, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
		has_many :answers, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy
		has_many :genre_to_smths, dependent: :destroy
		has_many :genres, through: :genre_to_smths, dependent: :destroy

		has_and_belongs_to_many :tags, :dependent => :destroy

    belongs_to :user
		belongs_to :category, optional: true
		belongs_to :post_type
		belongs_to :project, optional: true

		mount_uploader :image, ImageUploader

		after_create do
			post = Post.find_by(id: self.id)
			hashtags = self.content.scan(/#[\wWа-яА-Я]+/)
			hashtags.uniq.map do |hashtag|
				tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
				post.tags << tag
			end
		end

		before_update do
			post = Post.find_by(id: self.id)
			post.tags.clear
			hashtags = self.content.scan(/#[\wWа-яА-Я]+/)
			hashtags.uniq.map do |hashtag|
				tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
				post.tags << tag
			end
		end

		def self.tagged_with(name)
			Genre.find_by_name!(name).posts
		end

		def self.genre_counts
			Genre.select("genres.*, count(genre_to_smths.genre_id) as count").
			  joins(:genre_to_smths).group("genre_to_smths.genre_id")
		end

		def genre_list=(names)
			self.genres = genres.split(",").map do |n|
				Genre.where(name: n.strip).first_or_create!
			end
		end

end

app/models/post_type.rb
class PostType < ApplicationRecord
  has_many :categories
  has_many :genres
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :except => [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, except: [:index, :show, :get_posts_by_type, :post_type_page, :get_posts_by_type_and_genre]

  # GET /posts
  # GET /posts.json
  def index
    # Image.all.each { |i| i.image.recreate_versions! }
    # Post.all.each {|x|x.image.recreate_versions!}

    @categories = Category.all
    @genres = Genre.all
    @post_types = PostType.all
    @posts = Post.all.includes(:category, :genres, :likes, :favorites, :post_type).map do
      |post|
      post.as_json(include: [:category, :genres, :image, :likes, :favorites, :post_type])
    end


    @posts = Post.where(nil)
    filtering_params(params).each do |key, value|
      @posts = @posts.public_send("filter_by_#{key}", value) if value.present?
    end
    # if params.has_key?(:category)
    #   @category = Category.find_by_name(params[:category])
    #   @posts = Post.where(category: @category).includes(:category, :likes, :favorites).map do
    #     |post|
    #     post.as_json(include: [:category, :image, :likes, :favorites])
    #   end
    #   #render json: @posts, include: [:category]
    # else
    #   @posts = Post.all.includes(:category, :likes, :favorites).map do
    #     |post|
    #     post.as_json(include: [:category, :image, :likes, :favorites])
    #   end
    #   #render json: { posts: @posts }
    # end
  end
  #def current_user
  #  return unless session[:user_id]
  #  @current_user ||= User.find(session[:user_id])
  #end

  def post_type_page
    @post_type = PostType.find_by_name(params[:name])
    @categories = Category.all
    @post_types = PostType.all
    @category = params[:category]

      @genres = Genre.where(post_type_id:@post_type.id)

    render "posttypepage"
  end


  def get_posts_by_type

      @posts = Post.where(post_type_id: params[:post_type_id])
      if(params[:category])
        @category=Category.where(name:params[:category])
        @posts=@posts.where(category_id: @category[0].id)
      end
      @posts=@posts.includes(:category, :genres, :likes, :post_type).limit(params[:count])
      @posts=@posts.map do
        |post|
        post.as_json(include: [:category, :genres, :image, :likes, :post_type])
      end
      render json: @posts
  end

  def get_posts_by_type_and_genre
    @post_id=GenreToSmth.where(genre_id: params[:genre].split(',')).select("post_id")
      @posts = Post
      .where(post_type_id: params[:post_type_id])
      .where(id: @post_id)
      .includes(:category, :genres).map do
        |post|
        post.as_json(include: [:category, :genres, :image])
      end
      render json: @posts
  end

  def get_posts_by_type_and_user
      @posts = Post
      .where(post_type_id: params[:post_type_id])
      .where(user_id: params[:user_id])
      .includes(:category, :genres).map do
        |post|
        post.as_json(include: [:category, :genres, :image, :likes])
      end
      render json: @posts
  end


  # GET /posts/1
  # GET /posts/1.json
  def show
    @categories = Category.all
    if params.has_key?(:category)
      @category = Category.find(@post.category_id)
    end
    @post_genres=GenreToSmth.select("genre_id").where(post_id:@post.id)
    @comment = Comment.new
    @comment.post_id = @post.id
    @comment.user = current_user
    if @post.post_type.name == "puzzles"
      render 'showpuzzle'
    elsif @post.post_type.name == "Мастерская"
     render 'showuserpost'
    elsif @post.post_type.name == "Кладбище проектов"
     render 'shownecrology'
    else
      render 'show'
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.post_type = PostType.find_by_name("news")
  end

  def newnews
    @post = Post.new
    @post.post_type = PostType.find_by_name("Новости")
    @categories = [{id:"1", name:"Анонсы"}, {id:"2", name:"Релизы"}, {id:"3", name:"Обновления"}, {id:"4", name:"О компаниях"} ]
    @genres = [{id:"1", name:"Экшен"}, {id:"2", name:"Адвенчура"}, {id:"3", name:"Казуальная"}, {id:"4", name:"Многопользовательская"}, {id:"5", name:"Гонки"}, {id:"6", name:"РПГ"}, {id:"7", name:"Симулятор"}, {id:"8", name:"Спортивная"}, {id:"9", name:"Стратегия"}, {id:"10", name:"Хоррор"}, {id:"11", name:"Бесплатная"}, {id:"12", name:"Визуальная новелла"}, {id:"13", name:"Настольная"}]
    render 'newnews'
  end

  def newarticles
    @post = Post.new
    @post.post_type = PostType.find_by_name("Статьи")
    @categories = [{id:"5", name:"Факты"}, {id:"6", name:"Советы"}, {id:"7", name:"Чит-коды"} ]
    @genres = [{id:"18", name:"Факт"}, {id:"19", name:"Совет"}, {id:"20", name:"Чит-код"}]
    render 'newarticles'
  end

  def newreviews
    @post = Post.new
    @post.post_type = PostType.find_by_name("Обзоры")
    @categories = [{id:"8", name:"Экшен"}, {id:"9", name:"Адвенчура"}, {id:"10", name:"Казуальная"}, {id:"11", name:"Многопользовательская"}, {id:"12", name:"Гонки"}, {id:"13", name:"РПГ"}, {id:"14", name:"Симулятор"}, {id:"15", name:"Спортивная"}, {id:"16", name:"Стратегия"}, {id:"17", name:"Хоррор"}, {id:"18", name:"Бесплатная"}, {id:"19", name:"Визуальная новелла"}, {id:"20", name:"Настольные"} ]
    @genres = [{id:"1", name:"Экшен"}, {id:"2", name:"Адвенчура"}, {id:"3", name:"Казуальная"}, {id:"4", name:"Многопользовательская"}, {id:"5", name:"Гонки"}, {id:"6", name:"РПГ"}, {id:"7", name:"Симулятор"}, {id:"8", name:"Спортивная"}, {id:"9", name:"Стратегия"}, {id:"10", name:"Хоррор"}, {id:"11", name:"Бесплатная"}, {id:"12", name:"Визуальная новелла"}, {id:"13", name:"Настольная"} ]
    render 'newreviews'
  end

  def newnecrology
    @post = Post.new
    @post.post_type = PostType.find_by_name("Кладбище проектов")
    @categories = [{id:"8", name:"Экшен"}, {id:"9", name:"Адвенчура"}, {id:"10", name:"Казуальная"}, {id:"11", name:"Многопользовательская"}, {id:"12", name:"Гонки"}, {id:"13", name:"РПГ"}, {id:"14", name:"Симулятор"}, {id:"15", name:"Спортивная"}, {id:"16", name:"Стратегия"}, {id:"17", name:"Хоррор"}, {id:"18", name:"Бесплатная"}, {id:"19", name:"Визуальная новелла"}, {id:"20", name:"Настольная"} ]
    @genres = [{id:"1", name:"Экшен"}, {id:"2", name:"Адвенчура"}, {id:"3", name:"Казуальная"}, {id:"4", name:"Многопользовательская"}, {id:"5", name:"Гонки"}, {id:"6", name:"РПГ"}, {id:"7", name:"Симулятор"}, {id:"8", name:"Спортивная"}, {id:"9", name:"Стратегия"}, {id:"10", name:"Хоррор"}, {id:"11", name:"Бесплатная"}, {id:"12", name:"Визуальная новелла"}, {id:"13", name:"Настольная"}]
    render 'newnecrology'
  end

  def newportfolio
    @post = Post.new
    @post.post_type = PostType.find_by_name("Мастерская")
    @projects = Project.where(user_id: current_user.id)
    render 'newportfolio'
  end

  def hashtags
    tag = Tag.find_by(name: params[:name])
    @posts = tag.posts
  end

  # GET /posts/1/edit
  def edit
    @post_genres=GenreToSmth.select("genre_id").where(post_id:@post.id)
    if @post.post_type.name == "Новости"
      @categories = [{id:"1", name:"Анонсы"}, {id:"2", name:"Релизы"}, {id:"3", name:"Обновления"}, {id:"4", name:"О компаниях"} ]
      @genres = [{id:"14", name:"Анонс"}, {id:"15", name:"Релиз"}, {id:"16", name:"Обновление"}, {id:"17", name:"О компаниях"} ]
      render 'newreviews'
    elsif @post.post_type.name == "Статьи"
      @categories = [{id:"5", name:"Факты"}, {id:"6", name:"Советы"}, {id:"7", name:"Чит-коды"} ]
      @genres = [{id:"18", name:"Факт"}, {id:"19", name:"Совет"}, {id:"20", name:"Чит-код"}]
    else
      @categories = [{id:"8", name:"Экшен"}, {id:"9", name:"Адвенчура"}, {id:"10", name:"Казуальная"}, {id:"11", name:"Многопользовательская"}, {id:"12", name:"Приключения"}, {id:"12", name:"Гонки"}, {id:"13", name:"РПГ"}, {id:"14", name:"Симулятор"}, {id:"15", name:"Спортивная"}, {id:"16", name:"Стратегия"}, {id:"17", name:"Хоррор"}, {id:"18", name:"Бесплатная"}, {id:"19", name:"Визуальная новелла"}, {id:"20", name:"Настольная"} ]
      @genres = [{id:"1", name:"Экшен"}, {id:"2", name:"Адвенчура"}, {id:"3", name:"Казуальная"}, {id:"4", name:"Многопользовательская"}, {id:"5", name:"Гонки"}, {id:"6", name:"РПГ"}, {id:"7", name:"Симулятор"}, {id:"8", name:"Спортивная"}, {id:"9", name:"Стратегия"}, {id:"10", name:"Хоррор"}, {id:"11", name:"Бесплатная"}, {id:"12", name:"Визуальная новелла"}, {id:"13", name:"Настольная"} ]
      render 'newreviews'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @post.save

        # 1. Взять все жанры
        # 2. Сделать по жанрам цикл
        # 3. Внутри цикла для каждого id жанра проверять параметр genres[g_id]
        @genres = Genre.all

        # logger.debug params[:genres].to_s
        @genres.each do |genre|
          # logger.debug '"g_'+genre.id.to_s+'"=>"on"'
          # if params[:genres].to_s.includes?'"g_'+genre.id.to_s+'"=>"on"'
          if params[:genres].to_s.include?'"g_'+genre.id.to_s+'"=>"on"'
            GenreToSmth.new({genre_id: genre.id, post_id:@post.id}).save
          end
        end

        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        @genres = Genre.all
        GenreToSmth.where(post_id: @post.id).destroy_all

        @genres.each do |genre|
          # logger.debug '"g_'+genre.id.to_s+'"=>"on"'
          if params[:genres].to_s.include? '"g_'+genre.id.to_s+'"=>"on"'
            GenreToSmth.new({genre_id: genre.id, post_id:@post.id}).save
          end
        end

app/helpers/posts_helper.rb
module PostsHelper
  def render_with_hashtags(content)
    content.gsub(/#[\wWа-яА-Я]+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
  end
end

app/views/posts/_form.html.erb
<% @action = "/posts/"%>
  <%if @post.id%>
    <%if @post.id > 0%>
      <% @action = @action + @post.id.to_s %>
    <% end %>
  <% end %>

<form enctype="multipart/form-data" action=<%= @action %> accept-charset="UTF-8" method="post">
  <%= react_component 'O_postform', { post: @post, categories: @categories } %>

</form>

app/views/posts/_formarticles.html.erb
<% @action = "/posts/"%>
  <%if @post.id%>
    <%if @post.id > 0%>
      <% @action = @action + @post.id.to_s %>
    <% end %>
  <% end %>
  
<%= form_with(model: post, local: true) do |form| %>

  <%= react_component 'O_postform', { post: @post, categories: @categories } %>

<% end %>

app/views/posts/_formnews.html.erb
<% @action = "/posts/"%>
  <%if @post.id%>
    <%if @post.id > 0%>
      <% @action = @action + @post.id.to_s %>
    <% end %>
  <% end %>

<form enctype="multipart/form-data" action=<%= @action %> accept-charset="UTF-8" method="post">
  <%= react_component 'O_newsform', { post: @post, genres: @genres, active_genres: @post_genres, categories: @categories } %>

</form>

app/views/posts/_formportfolio.html.erb
<% @action = "/posts/"%>
  <%if @post.id%>
    <%if @post.id > 0%>
      <% @action = @action + @post.id.to_s %>
    <% end %>
  <% end %>
<form enctype="multipart/form-data" action="/posts" accept-charset="UTF-8" method="post">
  <%= react_component 'O_userpostform', { post: @post, categories: @categories, author: current_user, projects: @projects } %>
</form>

app/views/posts/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<% set_meta_tags title: 'Лабиринты CoroOne', description: 'Новости, статьи, проекты и многое другое'%>
<% set_meta_tags og: {
    title: ['Лабиринты CoroOne']
}  %>

<div class="Spider_section">
  <%= react_component 'M_post_types_nav', { post_types: @post_types } %>
  <% spider_post = @posts[0] %>
  <% news_banner = @posts[1] %>
  <% articles_banner = @posts[2] %>
  <% reviews_banner = @posts[3] %>
  <% spider_post_id = [] %>
  <% if spider_post %>
    <% spider_post_id.push(spider_post["id"])%>
  <% end %>

  <% if news_banner %>
    <% spider_post_id.push(news_banner["id"])%>
  <% end %>

  <% if articles_banner %>
    <% spider_post_id.push(articles_banner["id"])%>
  <% end %>

  <% if reviews_banner %>
    <% spider_post_id.push(reviews_banner["id"])%>
  <% end %>

  <% current_user_id = -1 %>
  <%if current_user%>
    <%current_user_id= current_user.id%>
  <% end %>

  <% if spider_post %>
    <%= react_component 'M_spider', { post: spider_post } %>
  <% end %>
</div>

    <div class="Post_type_section_wrapper">
      <%= react_component 'A_post_type', { post_type: @post_types[0] } %>
      <%= react_component 'O_news_preview', { post_type_id: 1, post_number: 17, remove_post: spider_post_id} %>
      <%= react_component 'M_more_info', {moreInfoType: "more_news"} %>
    </div>

    <% if news_banner %>
      <%= react_component 'M_post_preview', { post: news_banner, category: @posts[2]["category"], postStyle: 'ps--screen' } %>
    <% end %>

    <div class="Post_type_section_wrapper">
      <%= react_component 'A_post_type', { post_type: @post_types[1] } %>
      <%= react_component 'O_articles_preview', { post_type_id: 2, post_number: 14, remove_post: spider_post_id } %>
      <%= react_component 'M_more_info', {moreInfoType: "more_articles"} %>
    </div>

    <% if articles_banner %>
      <%= react_component 'M_post_preview', { post: articles_banner, category: @posts[2]["category"], postStyle: 'ps--screen' } %>
    <% end %>

    <div class="Post_type_section_wrapper">
      <%= react_component 'A_post_type', { post_type: @post_types[2] } %>
      <%= react_component 'O_reviews_preview', { post_type_id: 3, post_number: 10, remove_post: spider_post_id } %>
      <%= react_component 'M_more_info', {moreInfoType: "more_reviews"} %>
    </div>

    <% if reviews_banner %>
      <%= react_component 'M_post_preview', { post: reviews_banner, category: @posts[2]["category"], postStyle: 'ps--screen' } %>
    <% end %>

    <div class="Post_type_section_wrapper Without_shadow">
      <%= react_component 'A_post_type', { post_type: @post_types[4] } %>
      <%= react_component 'M_necro_add' %>
      <%= react_component 'O_necrologyposts_preview', { post_type_id: 5, post_number: 8 } %>
      <%= react_component 'M_more_info', {moreInfoType: "more_necrologies"} %>
    </div>

    <div class="Workshop_wrapper">
    <%= react_component 'A_post_type', { post_type: @post_types[3] } %>
    <%= react_component 'O_projects_preview', { current_user_id: current_user_id, genres: @genre, projectPlace: 'new' } %>

    <%= react_component 'S_userposts_preview', { post_type_id: 4, post_number: 13, current_user_id: current_user_id, user: current_user} %>
    </div>
    <br>

  <%= render 'footer/footerinner' %>

app/views/posts/new.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
      <h1>Новый пост</h1>

      <%= render 'form', post: @post, categories: @categories %>
      <%= link_to 'Назад', admin_context_path(curatorposts: "") %>
      <span><%= @errors %></span>
    </div>
  </div>
</body>

app/views/posts/newarticles.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
      <h1>Создание статьи</h1>
      <%= render 'form', post: @post, categories: @categories %>
      <%= link_to 'Назад', admin_context_path(curatorposts: "") %>
    </div>
  </div>
</body>

app/views/posts/newnecrology.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
      <%= react_component 'A_title', { title: "Некролог проекта", headingStyle: 'h2' } %>
      <%= render 'formnecrology', post: @post, categories: @categories %>
    </div>
  </div>
</body>

app/views/posts/newnews.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
      <%= react_component 'A_title', { title: "Создание новости", headingStyle: 'h2' } %>
      <%= render 'formnews', post: @post, categories: @categories %>
    </div>
  </div>
</body>

app/views/posts/newportfolio.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <%= react_component 'A_title', { title: "Новый пост", headingStyle: 'h2' } %>
    <%= render 'formportfolio', post: @post, author: current_user, projects: @projects %>
  </div>
</body>

app/views/posts/newreviews.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
      <h1>Создание обзора</h1>
      <%= render 'formreviews', post: @post, categories: @categories, genres: @genres %>
      <%= link_to 'Назад', admin_context_path(curatorposts: "") %>
    </div>
  </div>
</body>

app/views/posts/posttypepage.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

<% current_user_id = -1 %>
<%if current_user%>
  <%current_user_id= current_user.id%>
<% end %>

<% if @post_type[:id] == 1%>
<%= react_component 'T_news_preview', { genres: @genres, post_type_id: @post_type[:id], post_number: 110, category: @category, categories: @categories, post_types: @post_types } %>
<% end %>

<% if @post_type[:id] == 2%>
  <%= react_component 'T_articles_preview', { genres: @genres, post_type_id: @post_type[:id], post_number: 110, category: @category, categories: @categories, post_types: @post_types } %>
<% end %>

<% if @post_type[:id] == 3%>
  <%= react_component 'T_reviews_preview', { genres: @genres, post_type_id: @post_type[:id], post_number: 17, post_types: @post_types  } %>
<% end %>

<% if @post_type[:id] == 5%>
  <%= react_component 'M_post_types_nav', { post_types: @post_types } %>
  <div class="Post_type_section_wrapper Without_shadow">
    <%= react_component 'M_necro_add' %>
    <%= react_component 'O_necrologyposts_preview', { post_type_id: 5, post_number: 8 } %>
    <%= react_component 'M_more_info', {moreInfoType: "more_necrologies"} %>

    <% if user_signed_in? == true %>
      <%= react_component 'A_link', { link: "/posts/newnecrology", linkColor: 'link-create'}%>
    <% end %>
  </div>
<% end %>

<% if @post_type[:id] == 4%>
  <%= react_component 'M_post_types_nav', { post_types: @post_types } %>
  <div class="Workshop_wrapper">
  <%= react_component 'O_projects_preview', { current_user_id: current_user_id, genres: @genre, projectPlace: 'new' } %>
  <a class="wishes" href=""><p>Хочу попасть сюда!</p></a>
  <%= react_component 'S_userposts_preview', { post_type_id: 4, post_number: 13, current_user_id: current_user_id, user: current_user} %>
  </div>
<% end %>

  <%= render 'footer/footerinner' %>

app/views/posts/shownecrology.html.erb
<body class="show_body">

      <%= react_component 'M_necrology_view', { category: @category, categories: @categories, post: @post, post_type: @post.post_type, category: @post.category } %>


      <div class="comments">

      <%= react_component 'A_title', { headingStyle: "h3", headingColor: "mineral-gray", title: "Комментарии", headingAlign: "left_align"} %>

      <% topComments = @post.comments.select{|c| ! c.parent_id} %>
      <%= render topComments %>

      <% if user_signed_in? %>
        <%= render "comments/form" %>
      <% else %>
        <p className="please">Пожалуйста, <%= link_to 'login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> чтобы комментировать</p>
      <% end %>

      <% if user_signed_in? %>
      <%= link_to 'Редактировать', edit_post_path(@post) %> |
      <% end %>
      <%= link_to 'Назад', admin_context_path(curatorposts: "") %>

      </div>

</body>

app/views/posts/showpuzzle.html.erb
<body class="show_body">
  <%= render 'navbar/navbarleft' %>
  <div class="wrapper_show">
    <div class="narrow">
      <% if @post.category_id? %>
          <span>
            <%= @post.category.name %>
          </span>
      <% end %>
      <h1>
        <%= @post.title %>
      </h1>

      <%= image_tag(@post.image.url, alt: 'Image') if @post.image? %>
        <p>
          <strong></strong>
          <%= @post.content.html_safe %>
        </p>
      </div>

      <h2>Ответы</h2>
        <%= render @post.answers %>
      <% if user_signed_in? %>
      <%= link_to 'Редактировать', edit_post_path(@post) %> |
      <% end %>
      <%= link_to 'Назад', admin_context_path(curatorposts: "") %>

  </div>
</body>