config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :projects
  resources :post_types
  resources :follows
  resources :categories
  resources :genres
  # resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  post 'users/:id/edit', to: "users#update"
  post 'posts/:id', to: "posts#update"
  get 'users/:id/getuser', to: "users#getuser"
  get 'post_types/:id/getpost_type', to: "post_types#getpost_type"
  post 'users/:id/delete', to: "users#delite"
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"
  # get 'about/index'
  # get 'promo/index'
resources :posts do
    collection do
      get :newshit
      get :newarticles
      get :newnews
      get :newpuzzles
      get :newreviews
      get :newportfolio
      get :newevents
      get :newnecrology
    end
    resources :answers
    resources :comments
    resources :likes
    resources :favorites
end
  resources :subscribers
  get 'posts/index'

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'admin_context', to: 'admin_context#index'
  root 'promo#index'

  get "search", to: "search#search"

  get "searchpage" => "search#index", as: "search_index"

  get '/posts/hashtag/:name', to: 'posts#hashtags'

  get '/posts_by_type/:post_type_id/count/:count', to: "posts#get_posts_by_type"

  get '/posts_by_type_and_genre/:post_type_id/genre/:genre', to: "posts#get_posts_by_type_and_genre"

  get '/posts_by_type_and_user/:post_type_id/user/:user_id', to: "posts#get_posts_by_type_and_user"

  get '/projects_by_user/:user_id', to: "projects#get_projects_by_user"

  get '/newest_projects', to: "projects#get_newest_projects"

  get '/posts_by_category/:post_type_id/category/:category_id', to: "posts#get_posts_by_category"

  get '/posts/by_type/:name', to:"posts#post_type_page"


  # get `/your/api/namespace/endpoint/:withDynamicString/:forParams`, to: "posts#upload_image"

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  get 'users/:id/edit' => 'users#edit'
  get 'users/:id/favorites', to: 'users#favorites'
  post 'posts/:id' => 'posts#edit'
  delete 'users/:id', to: 'users#destroy'
  get 'users/:id/following', :to => "users#following", :as => :following

  resources :projects do
      resources :developers
  end
  # delete 'comments/:id', to: 'comments#destroy'
  # root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :post_type
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @categories = Category.all
    @post_types = [{id:"1", name:"Новости"}, {id:"2", name:"Статьи"}, {id:"3", name:"Обзоры"}, {id:"4", name:"Мастерская"}, {id:"5", name:"Кладбище проектов"} ]
  end

  # GET /categories/1/edit
  def edit
    @post_types = [{id:"1", name:"Новости"}, {id:"2", name:"Статьи"}, {id:"3", name:"Обзоры"}, {id:"4", name:"Мастерская"}, {id:"5", name:"Кладбище проектов"} ]
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :post_type_id, :description, :display_in_navbar, :imagesrc)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <%= react_component 'M_catform', { category: @category, post_types: @post_types } %>
<% end %>

app/views/categories/edit.html.erb
<body class="edit_post">
   <div class="edit_post_wrapper">
     <div class="edit_post_card">
      <h1>Редактирование категории</h1>

      <%= render 'form', category: @category %>

      <%= link_to 'Открыть', @category %> |
      <%= link_to 'Назад', admin_context_path(categories: "") %>
    </div>
  </div>
</body>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<%= react_component 'M_categories_nav', { categories: @categories } %>
<br>
<%= react_component 'M_cat_preview', { categories: @categories } %>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<body class="new_post">
  <div class="new_post_wrapper">
    <div class="new_post_card">
    <h1>Новая категория</h1>

    <%= render 'form', category: @category, post_types: @post_types %>
    <%= link_to 'Назад', admin_context_path(categories: "") %>
  </div>
</div>
</body>

app/views/categories/show.html.erb
<body class="show_body">
  <div class="wrapper_show">

    <p id="notice"><%= notice %></p>
    <%= react_component 'M_catview', { category: @category } %>
      <%= link_to 'Редактировать', edit_category_path(@category) %> |
      <%= link_to 'Назад', admin_context_path(categories: "") %>
    </div>
</body>